"""add_asset_table

Revision ID: 1962683fd6bf
Revises: 7c1c9f8d6b02
Create Date: 2025-10-04 00:28:32.836948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1962683fd6bf'
down_revision: Union[str, None] = '7c1c9f8d6b02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # Create enum type if it doesn't exist
    op.execute("DO $$ BEGIN CREATE TYPE assettype AS ENUM ('MEDIA', 'MODEL', 'STYLE'); EXCEPTION WHEN duplicate_object THEN null; END $$;")
    
    # Create asset_type_enum for use in table
    asset_type_enum = postgresql.ENUM('MEDIA', 'MODEL', 'STYLE', name='assettype', create_type=False)
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('object_path', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('bucket_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('asset_type', asset_type_enum, nullable=False),
    sa.Column('style_subcategory', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('source_model_ids', sa.JSON(), nullable=True),
    sa.Column('source_style_id', sa.Uuid(), nullable=True),
    sa.Column('refined_prompt', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_style_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_asset_type'), 'asset', ['asset_type'], unique=False)
    op.create_index(op.f('ix_asset_created_at'), 'asset', ['created_at'], unique=False)
    op.create_index(op.f('ix_asset_is_active'), 'asset', ['is_active'], unique=False)
    op.create_index(op.f('ix_asset_object_path'), 'asset', ['object_path'], unique=True)
    op.create_index(op.f('ix_asset_session_id'), 'asset', ['session_id'], unique=False)
    op.create_index(op.f('ix_asset_style_subcategory'), 'asset', ['style_subcategory'], unique=False)
    op.create_index(op.f('ix_asset_user_id'), 'asset', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asset_user_id'), table_name='asset')
    op.drop_index(op.f('ix_asset_style_subcategory'), table_name='asset')
    op.drop_index(op.f('ix_asset_session_id'), table_name='asset')
    op.drop_index(op.f('ix_asset_object_path'), table_name='asset')
    op.drop_index(op.f('ix_asset_is_active'), table_name='asset')
    op.drop_index(op.f('ix_asset_created_at'), table_name='asset')
    op.drop_index(op.f('ix_asset_asset_type'), table_name='asset')
    op.drop_table('asset')
    # ### end Alembic commands ###
