"""add new agents table

Revision ID: 49fd23a3918f
Revises: e2a1af2c63a1
Create Date: 2025-09-04 16:53:44.012543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '49fd23a3918f'
down_revision: Union[str, None] = 'e2a1af2c63a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('app_name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('agent', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='agentstatus'), nullable=False),
    sa.Column('turn_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_agent'), 'agents', ['agent'], unique=False)
    op.create_index(op.f('ix_agents_app_name'), 'agents', ['app_name'], unique=False)
    op.create_index(op.f('ix_agents_session_id'), 'agents', ['session_id'], unique=False)
    op.create_index(op.f('ix_agents_status'), 'agents', ['status'], unique=False)
    op.create_index(op.f('ix_agents_user_id'), 'agents', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agents_user_id'), table_name='agents')
    op.drop_index(op.f('ix_agents_status'), table_name='agents')
    op.drop_index(op.f('ix_agents_session_id'), table_name='agents')
    op.drop_index(op.f('ix_agents_app_name'), table_name='agents')
    op.drop_index(op.f('ix_agents_agent'), table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###
